name: build-docker-image-Workflow
on: workflow_dispatch
jobs:
  build-it-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello Robert!"
      - name: Print goodbye
        run: echo "Done - bye!"
